### ISSUE TITLE
Missing gulp tasks tests

### ISSUE THREAD

**Issue by diegoaguilar** [mike3run/ground-zero#2]
I suggest you adding any simple tests set for the general feature and capabilities on ground zero, I think @poguez would guide on collaboration and I'd be happy to help a bit on JS testing too.

**Comment by shelldandy** [comment]
Si he querido hacer eso pero no tengo idea de como se le hacen unit tests a tasks de gulp sniff como le podríamos hacer @diegoaguilar @poguez ?

**Comment by diegoaguilar** [comment]
We've got unit tests:

Decoupled functions working in favor of your module's logic can be tested here. _If you have a function which receives pasta, it must return spaghetti_ you test that function, also you may want to check if it's ready to handle unexpected cases, like receiving meat. 

Those functions should exist in small modules outside code Gulp API functions calls.

Apart, we may have other kind of tests where we prepare a set of resources (JS files, images, etc) and make our test runner execute Gulp and when it's done, we check output is the expected one.

So, for a start, is ground-zero ready for unit testing?

Sorry about english, I ain't chicano but keep using english for work anytime.

**Comment by shelldandy** [comment]
gotcha, so maybe the way to go should be to make a separate file/folder with only the tasks so i can require them in both the gulp tasks and the unit tests amirite?

**Comment by diegoaguilar** [comment]
Yes, that's it. I'll take a look to your code ASAP, please point me to any
lines along your code where most important logic exists.

**Comment by shelldandy** [comment]
Mostly all of the logic is inside the `gulp/tasks` folder each task lives on its own file

**Comment by shelldandy** [comment]
@diegoaguilar check the `adding-tests` branchs im starting to decouple the important tasks like scripts, sass & pug ⛄
