### ISSUE TITLE
Deprecate use of bower in favour of npm

### ISSUE THREAD

**Issue by shelldandy** [mike3run/ground-zero#6]
Maybe using some ES6 in the frontend as well for extra-crispyness

**Comment by diegoaguilar** [comment]
Already confirmed you can get all your deps from npm or in the proper format (`package.json` can get a git url as dependency version)? 

```
  "dependencies": {
    "jquery": "^2.2.2",
    "modular-scale": "^2.1.1",
    "manila-mixins": "*",
    "svg4everybody": "^2.1.0",
    "bem-constructor": "^1.1.0"
  }
```
